### ISSUE TITLE
Connection to server got closed. Server will restart.

### ISSUE THREAD

**Issue by oblitum** [voldikss/coc-lsp-wl#4]
Hi, I'm on Linux and I'm trying coc-lsp-wl but I'm only getting "Connection to server got closed. Server will restart." in `:CocInfo`.

Output: https://gist.github.com/oblitum/4e8489a0205ec49650046a005c9f9c7f

I also often get the following on subsequent `:CocInfo`

```
## Output channel: lsp-wl

[Error  - 5:41:20 PM] Connection to server is erroring. Shutting down server.
[Trace - 5:41:20 PM] Sending request 'shutdown - (1)'.
[Error  - 5:41:20 PM] Connection to server is erroring. Shutting down server.
[Error  - 5:41:20 PM] Connection to server is erroring. Shutting down server.
[Error  - 5:41:20 PM] Connection to server is erroring. Shutting down server.
[Error  - 5:41:20 PM] Connection to server is erroring. Shutting down server.
```

**Comment by oblitum** [comment]
I've initially [reported it to the server project](https://github.com/kenkangxgwe/lsp-wl/issues/9) but I think it may be worth checking here first.

**Comment by voldikss** [comment]
What's your configuration of this extension in coc-settings.json?

**Comment by oblitum** [comment]
I don't do my configuration in coc-settings.json, I do it from `.vimrc` on `VimEnter` like the following:

```vim
  call coc#config('lsp-wl', {
  \   'wolframLanguageServerPath': '/home/francisco/Projects/lsp-wl'
  \ })
```

**Comment by oblitum** [comment]
mathematica is 11.2.0.

**Comment by voldikss** [comment]
Hmmm, Have you tried running the server out of Vim?

According to the doc of lsp-wl [here](https://github.com/kenkangxgwe/lsp-wl#run-the-server)
```
wolfram -script /path/to/lsp-wl/init.wls [args]
# or
wolframscript -f /path/to/lsp-wl/init.wls [args]
```

**Comment by voldikss** [comment]
Or maybe the port was not opened?

**Comment by oblitum** [comment]
For testing from command line I had to do this on one terminal:

```
~ ❯❯❯ wolfram -script Projects/lsp-wl/init.wls --tcp-server
[INFO  2019-07-30T01:31:44] Initializing Wolfram Language Server
[INFO  2019-07-30T01:31:45] Language server is connecting the client through
tcp-server.
[INFO  2019-07-30T01:31:45] Server listening on port 6536...
```

And this on another:

```
~ ❯❯❯ wolfram -script Projects/lsp-wl/init.wls
[INFO  2019-07-30T01:31:53] Language server is connecting the client through
socket.
[INFO  2019-07-30T01:31:53] Server listening from port 6536...
```

Then the first terminal shows

```
[INFO  2019-07-30T01:31:53] Client connected
```

So, it seems to be working. Simply calling `wolfram -script Projects/lsp-wl/init.wls` alone doesn't work, I get an error:

```
~ ❯❯❯ wolfram -script Projects/lsp-wl/init.wls
[INFO  2019-07-30T01:31:28] Initializing Wolfram Language Server
[INFO  2019-07-30T01:31:28] Language server is connecting the client through
socket.

SocketConnect::zmqexception:
   A ZeroMQLink exception was thrown - Connection refused (code 111)
[ERROR 2019-07-30T01:31:28] Cannot connect to client via socket.
```

Which simply seems like a client missing a server.

---

As for opening ports, I didn't open any port on my firewall because I thought only loopback access was needed, so no need to open ports, and given that the above terminal interaction seemed to work and on `:CocInfo` I've posted first I also got this:

```
[INFO  2019-07-29T17:36:02] Server listening from port 6536...
[Trace - 5:36:03 PM] Received response 'initialize - (0)' in 427ms.
Result: {
    "capabilities": {
        "textDocumentSync": 2,
        "hoverProvider": true,
        "completionProvider": {
            "resolveProvider": true,
            "triggerCharacters": "\\"
        },
        "documentSymbolProvider": true
    }
```

It looked like coc got a first response, but then the server closes when a `textDocument/didOpen` is sent.

**Comment by voldikss** [comment]
Hmmmm sorry I actually doesn't know lsp too much. This extension was ported from vscode-lsp-wl but I don't know much more detail about the mechanism.

**Comment by oblitum** [comment]
Hmm, ok then :-/

**Comment by kenkangxgwe** [comment]
> Simply calling wolfram -script Projects/lsp-wl/init.wls alone doesn't work, I get an error: 

When you pass no extra arguments into the server, it will run as a socket client and try to connect to a socket server at the default port (6536). In your case, the connection will be refused. If you want to run it as a socket server, you should pass the `--tcp-server=<port>` argument.

**Comment by kenkangxgwe** [comment]
@voldikss, I confirm that it is an upstream problem. You can close the issue now.
